### ISSUE TITLE
[Question] TBMQ and TBPE in the same machine installation - PostgreSQL access error

### ISSUE THREAD

**Issue by patobalbi** [thingsboard/tbmq#141]
**TBMQ and TBPE in the same machine installation**

I have some problems when I want to install TBMQ in the same machine where TBPE is running. I'm using Linux (ubuntu 20.04) running on azure cloud.

I installed TBMQ with no problems in other machines, but in this one seems like the docker container from TBMQ is not able to open Postgres DB in the other container.

The installation enters inside a loop where it never finishes.

I changed the ports inside the docker compose to avoid any port conflict:

![image](https://github.com/user-attachments/assets/c9f20ec9-b223-4cbb-b8e1-8ba14677a8e6)

and the docker compose log-in and other data is not modified.

![image](https://github.com/user-attachments/assets/783c1cec-ddb6-49e1-ade6-abac30e7cfdf)

TBPE also uses POSTGRESQL it is necessary to change that port as well?

Thank you.

Here is the installation loop I described before:

`tbmq-1  |  ===================================================
tbmq-1  |  :: ThingsBoard MQTT Broker ::       (v1.3.0)
tbmq-1  |  ===================================================
tbmq-1  |
tbmq-1  | HV000001: Hibernate Validator 6.0.20.Final
tbmq-1  | Starting ThingsboardMqttBrokerInstallApplication v1.3.0 using Java 17.0.6 on 7960e578d814 with PID 6 (/usr/share/thingsboard-mqtt-broker/bin/thingsboard-mqtt-broker.jar started by thingsboard in /)
tbmq-1  | The following 1 profile is active: "install"
tbmq-1  | Multiple Spring Data modules found, entering strict repository configuration mode
tbmq-1  | Bootstrapping Spring Data JPA repositories in DEFAULT mode.
tbmq-1  | Finished Spring Data repository scanning in 469 ms. Found 13 JPA repository interfaces.
tbmq-1  | HHH000204: Processing PersistenceUnitInfo [name: default]
tbmq-1  | HHH000412: Hibernate ORM core version 5.6.15.Final
tbmq-1  | HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
tbmq-1  | HikariPool-1 - Starting...
tbmq-1  | HikariPool-1 - Exception during pool initialization.
tbmq-1  | org.postgresql.util.PSQLException: The connection attempt failed.
tbmq-1  |       at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
tbmq-1  |       at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
tbmq-1  |       at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
tbmq-1  |       at org.postgresql.Driver.makeConnection(Driver.java:434)
tbmq-1  |       at org.postgresql.Driver.connect(Driver.java:291)
tbmq-1  |       at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
tbmq-1  |       at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
tbmq-1  |       at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
tbmq-1  |       at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
tbmq-1  |       at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
tbmq-1  |       at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
tbmq-1  |       at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
tbmq-1  |       at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
tbmq-1  |       at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
tbmq-1  |       at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
tbmq-1  |       at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
tbmq-1  |       at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)
tbmq-1  |       at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)
tbmq-1  |       at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)
tbmq-1  |       at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)
tbmq-1  |       at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)
tbmq-1  |       at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)
tbmq-1  |       at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
tbmq-1  |       at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
tbmq-1  |       at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
tbmq-1  |       at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
tbmq-1  |       at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
tbmq-1  |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
tbmq-1  |       at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1156)
tbmq-1  |       at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:910)
tbmq-1  |       at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
tbmq-1  |       at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
tbmq-1  |       at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
tbmq-1  |       at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
tbmq-1  |       at org.thingsboard.mqtt.broker.ThingsboardMqttBrokerInstallApplication.main(ThingsboardMqttBrokerInstallApplication.java:47)
tbmq-1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tbmq-1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tbmq-1  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tbmq-1  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tbmq-1  |       at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
tbmq-1  |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
tbmq-1  |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
tbmq-1  |       at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
tbmq-1  | Caused by: java.net.SocketTimeoutException: Connect timed out
tbmq-1  |       at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
tbmq-1  |       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
tbmq-1  |       at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
tbmq-1  |       at java.base/java.net.Socket.connect(Socket.java:633)
tbmq-1  |       at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
tbmq-1  |       at org.postgresql.core.PGStream.<init>(PGStream.java:98)
tbmq-1  |       at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
tbmq-1  |       at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
tbmq-1  |       ... 55 common frames omitted
tbmq-1  | HHH000342: Could not obtain connection to query metadata
tbmq-1  | org.postgresql.util.PSQLException: The connection attempt failed.
tbmq-1  |       at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
tbmq-1  |       at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
tbmq-1  |       at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
tbmq-1  |       at org.postgresql.Driver.makeConnection(Driver.java:434)
tbmq-1  |       at org.postgresql.Driver.connect(Driver.java:291)
tbmq-1  |       at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
tbmq-1  |       at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
tbmq-1  |       at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
tbmq-1  |       at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
tbmq-1  |       at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
tbmq-1  |       at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
tbmq-1  |       at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
tbmq-1  |       at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
tbmq-1  |       at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181)
tbmq-1  |       at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68)
tbmq-1  |       at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
tbmq-1  |       at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:272)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:246)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)
tbmq-1  |       at org.hibernate.id.factory.internal.DefaultIdentifierGeneratorFactory.injectServices(DefaultIdentifierGeneratorFactory.java:175)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.injectDependencies(AbstractServiceRegistryImpl.java:295)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:252)
tbmq-1  |       at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:223)
tbmq-1  |       at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.<init>(InFlightMetadataCollectorImpl.java:173)
tbmq-1  |       at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:127)
tbmq-1  |       at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1460)
tbmq-1  |       at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1494)
tbmq-1  |       at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
tbmq-1  |       at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
tbmq-1  |       at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
tbmq-1  |       at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
tbmq-1  |       at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
tbmq-1  |       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
tbmq-1  |       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
tbmq-1  |       at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1156)
tbmq-1  |       at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:910)
tbmq-1  |       at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
tbmq-1  |       at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
tbmq-1  |       at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
tbmq-1  |       at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
tbmq-1  |       at org.thingsboard.mqtt.broker.ThingsboardMqttBrokerInstallApplication.main(ThingsboardMqttBrokerInstallApplication.java:47)
tbmq-1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tbmq-1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tbmq-1  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tbmq-1  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tbmq-1  |       at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
tbmq-1  |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
tbmq-1  |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
tbmq-1  |       at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
tbmq-1  | Caused by: java.net.SocketTimeoutException: Connect timed out
tbmq-1  |       at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
tbmq-1  |       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
tbmq-1  |       at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
tbmq-1  |       at java.base/java.net.Socket.connect(Socket.java:633)
tbmq-1  |       at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
tbmq-1  |       at org.postgresql.core.PGStream.<init>(PGStream.java:98)
tbmq-1  |       at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
tbmq-1  |       at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
tbmq-1  |       ... 55 common frames omitted
tbmq-1  | HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
tbmq-1  | HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
tbmq-1  | Initialized JPA EntityManagerFactory for persistence unit 'default'
tbmq-1  | Started ThingsboardMqttBrokerInstallApplication in 30.413 seconds (JVM running for 32.953)
tbmq-1  | Starting TBMQ Installation...
tbmq-1  | Installing DataBase schema...
tbmq-1  | Installing SQL DataBase schema part: schema-entities.sql
tbmq-1  | Unexpected error during TBMQ installation!
tbmq-1  | org.postgresql.util.PSQLException: The connection attempt failed.
tbmq-1  |       at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:354)
tbmq-1  |       at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
tbmq-1  |       at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
tbmq-1  |       at org.postgresql.Driver.makeConnection(Driver.java:434)
tbmq-1  |       at org.postgresql.Driver.connect(Driver.java:291)
tbmq-1  |       at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
tbmq-1  |       at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
tbmq-1  |       at org.thingsboard.mqtt.broker.service.install.AbstractDatabaseSchemaService.executeQueryFromFile(AbstractDatabaseSchemaService.java:72)
tbmq-1  |       at org.thingsboard.mqtt.broker.service.install.AbstractDatabaseSchemaService.createDatabaseSchema(AbstractDatabaseSchemaService.java:58)
tbmq-1  |       at org.thingsboard.mqtt.broker.install.ThingsboardMqttBrokerInstallService.performInstall(ThingsboardMqttBrokerInstallService.java:78)
tbmq-1  |       at org.thingsboard.mqtt.broker.ThingsboardMqttBrokerInstallApplication.main(ThingsboardMqttBrokerInstallApplication.java:48)
tbmq-1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
tbmq-1  |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
tbmq-1  |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
tbmq-1  |       at java.base/java.lang.reflect.Method.invoke(Method.java:568)
tbmq-1  |       at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
tbmq-1  |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
tbmq-1  |       at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
tbmq-1  |       at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
tbmq-1  | Caused by: java.net.SocketTimeoutException: Connect timed out
tbmq-1  |       at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
tbmq-1  |       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
tbmq-1  |       at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
tbmq-1  |       at java.base/java.net.Socket.connect(Socket.java:633)
tbmq-1  |       at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
tbmq-1  |       at org.postgresql.core.PGStream.<init>(PGStream.java:98)
tbmq-1  |       at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
tbmq-1  |       at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
tbmq-1  |       ... 18 common frames omitted
tbmq-1  | [TimeseriesQueue] Queue polling was interrupted.
tbmq-1  | [TimeseriesQueue] Queue polling was interrupted.
tbmq-1  | [TimeseriesQueue] Queue polling was interrupted.
tbmq-1  | [UpdatePacketTypeQueue] Queue polling was interrupted.
tbmq-1  | [UpdatePacketTypeQueue] Queue polling was interrupted.
tbmq-1  | [DeletePacketQueue] Queue polling was interrupted.
tbmq-1  | [UpdatePacketTypeQueue] Queue polling was interrupted.
tbmq-1  | [DeletePacketQueue] Queue polling was interrupted.
tbmq-1  | [DeletePacketQueue] Queue polling was interrupted.
tbmq-1  | Closing JPA EntityManagerFactory for persistence unit 'default'
tbmq-1  | Unexpected error during TBMQ installation!
tbmq-1  | ERROR: TBMQ is not installed
tbmq-1 exited with code 0`

**Comment by dmytro-landiak** [comment]
HI @patobalbi,

Could you please clarify which deployment method you used for the TBPE installation? You can find the options here: [TBPE Installation Options](https://thingsboard.io/docs/user-guide/install/pe/installation-options/) (please give me the link for the used deployment).

At this point, it's difficult to determine the exact issue, but it seems there might be a conflict/misconfiguration between the TBPE and TBMQ installations.

**Comment by dmytro-landiak** [comment]
I am closing this issue due to inactivity. Please feel free to reopen it if it is still relevant and you have any more questions.
